[tools]
node      = "23.9.0"
npm       = "11.1.0"
watchexec = "latest"

[tasks.api-server]
description = "Start Bitburner remote files API server"
run         = "npm run watch"

[tasks.install-deps]
run = "npm install"
